### Find All Content
GET http://localhost:8080/messages

### Get Content by ID
GET http://localhost:8080/messages?id=3

### GET Content by Username
GET http://localhost:8080/messages?username=rati

### Create New Content
POST http://localhost:8080/messages
Content-Type: application/json

{
  "username": "masho",
  "password": "mashomasho",
  "body": "Created a new message"
}

### Update Existing Content
PUT http://localhost:8080/messages
Content-Type: application/json

{
  "username": "masho",
  "password": "incorrect password",
  "messageId": 3,
  "body": "This is the body of the newly updated content."
}

### Delete Content
DELETE http://localhost:8080/messages
Content-Type: application/json

{
  "username": "gio",
  "password": "giopio",
  "messageId": 4
}